[package]
name = "fuzzilua-mutate"
version = "0.1.0"
edition = "2024"

[dependencies]
fuzzilua-ir = { workspace = true }
fuzzilua-gen = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
test-case = { workspace = true }

[[bench]]
name = "splice_ranges"
harness = false

